# SPDX-FileCopyrightText: Copyright 2024 U Servers Comunicaciones, S.C.
# SPDX-License-Identifier: Apache-2.0

name: golangci-lint

on:
  pull_request:

permissions: {}

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: 89476e7a1eaa0a8a06c17343af960a5fd9e7edb7 # v1.62.2
          install-mode: goinstall
          args: --timeout=5m
